spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hbstudent?useUnicode=true&characterEncoding=utf-8
    username: hbstudent
    password: hbstudent
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.lrm.blog: info
  file: log/blog-pro.log

server:
  port: 8081
